### ISSUE TITLE
UTF-16 character issues.

### ISSUE THREAD

**Issue by kalaspuffar** [liblouis/liblouis-java#20]
Hi @bertfrees 

Found an issue with one book and dotify library. When we tried to translate an English book with an alpha character. This char is a multi char that will give us one codepoint but multiple characters when asking for string length.

I will submit a test case that showcases the issue.

https://en.wikipedia.org/wiki/UTF-16#Code_points_from_U+010000_to_U+10FFFF

Best regards
Daniel

**Comment by AlexanderHugestrand** [comment]
More specifically, in this case we had two 16-bit values that encode a single character and codepoint: \uD835\uDEFC

**Comment by bertfrees** [comment]
Thanks.

Actually liblouis-java expects that the length of the "characterAttributes" argument is the same as the length of the Java string (char array), not the number of code points in the string. But I found out now that I was doing it all wrong and the "typeform" and ""characterAttributes" arguments were just not working when the input had Unicode characters above U+FFFF.

Will be fixed in the next release.

**Comment by bertfrees** [comment]
Fixed by commits aa08131 and 4b9cc74.
